[program:example_app]
command=/bin/sh -c "%(ENV_PROJECT_ROOT)s/deploy/scripts/run_example_app.sh"
directory=%(ENV_PROJECT_ROOT)s
autostart=true
autorestart=true
startsecs=3
startretries=10
stderr_logfile=/var/log/example_app.err.log
stdout_logfile=/var/log/example_app.out.log
environment=PROJECT_ROOT="%(ENV_PROJECT_ROOT)s",APP_ARGS="%(ENV_APP_ARGS)s"
