name = "webframework"
description = "Ada-first server-driven web framework using HTTP/1.1 and WebSockets"
version = "0.1.0-dev"
licenses = "MIT"
website = "https://github.com/bracke/webframework"
tags = ["web", "websocket", "http", "server-driven"]

[[depends-on]]
gnat_native = "=15.2.1"

[[depends-on]]
cryptolib = "*"

[[depends-on]]
ssh_lib = "*"

[[depends-on]]
zlib = "*"

[[depends-on]]
terminal_styles = "*"

[[pins]]
cryptolib = { path = "../cryptolib" }

[[pins]]
ssh_lib = { path = "../sshlib" }

[[pins]]
zlib = { path = "../zlib" }

[[pins]]
terminal_styles = { path = "../terminal_styles" }
